# sets up postgres, replaced with vertica-ce
# to run in ci.yml, replace vertica logic with - run: docker compose up -d
version: '2'
services:
  postgres:
    image: postgres:14
    ports:
      - 5433:5433
    volumes:
      - ./docker/sql_setup.sh:/docker-entrypoint-initdb.d/sql_setup.sh
    environment:
      POSTGRES_PASSWORD: postgres
